service: TakeUforward
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 2048
  region: ap-south-1

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      MYSQL_HOST: mysql-84d76a2-sushilrawat1720-ea0b.a.aivencloud.com
      MYSQL_USER: avnadmin
      MYSQL_PASS: AVNS_ovZSRuLFyl3P_S0vd7j
      MYSQL_DATABASE: code_app
      MYSQL_PORT: 25864
